ci: unique artifact name for junit reports in kind workflow
[ cherry-picked from cilium/cilium-cli repository ]

Due to some recent changes on GitHub's side, uploading the JUnit reports
on the second job to finish in the kind workflow will fail with:

    Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

Avoid this from happing by giving the artifacts unique names.

Fixes #2222

Signed-off-by: Tobias Klauser <tobias@cilium.io>