cli: adapt helm chart cleanup of deprecated hubble values
[ cherry-picked from cilium/cilium-cli repository ]

Deprecated Cilium Helm Chart values have been removed in the PR
https://github.com/cilium/cilium/pull/24214.

Installing Cilium (`cilium install`) & enabling hubble (`cilium hubble
enable`) will break the connectivity from the hubble relay to the peer
service (`Failed to create peer client for peers synchronization...`).

This will consequently also fail the connectivity tests with the following
error: `Timeout waiting for flow listener to become ready`.

We need to set `tls.ca.cert` & `tls.ca.key` during `cilium hubble enable`
to use the same CA cert.

Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>